const BD=[{id:'g',name:'一般詞彙',color:'#7c6af7'},{id:'v1',name:'一類動詞',color:'#10b981'},{id:'v2',name:'二類動詞',color:'#059669'},{id:'v3',name:'三類動詞',color:'#047857'},{id:'adj',name:'形容詞',color:'#f472b6'},{id:'n',name:'名詞',color:'#60a5fa'}];
const S={view:'home',theme:'dark',tab:'i',words:[],banks:[...BD],favorites:[],favTab:'all',libTab:'all',modal:null,iBid:'g',qBids:[],qW:[],qi:0,qF:false,qM:'jp',qSrc:'all',qC:10,qNF:0,sk:'',fsk:'',delTask:null};
function sv(){localStorage.setItem('tw',JSON.stringify(S.words));localStorage.setItem('tf',JSON.stringify(S.favorites));localStorage.setItem('tb',JSON.stringify(S.banks));localStorage.setItem('tt',S.theme);}
function ld(){try{S.words=JSON.parse(localStorage.getItem('tw'))||[];}catch{S.words=[];}try{S.favorites=JSON.parse(localStorage.getItem('tf'))||[];}catch{S.favorites=[];}try{const b=JSON.parse(localStorage.getItem('tb'));if(b&&b.length)S.banks=b;}catch{}let mig=false;if(!S.banks.some(b=>b.id==='v1')){S.banks=S.banks.filter(b=>b.id!=='v');S.banks.splice(1,0,{id:'v1',name:'一類動詞',color:'#10b981'},{id:'v2',name:'二類動詞',color:'#059669'},{id:'v3',name:'三類動詞',color:'#047857'});mig=true;}if(mig){S.words.forEach(w=>{if(w.bankId==='v')w.bankId='v1';});S.favorites.forEach(w=>{if(w.bankId==='v')w.bankId='v1';});sv();}S.theme=localStorage.getItem('tt')||'dark';document.documentElement.setAttribute('data-theme',S.theme);}
let _tt;
function toast(m,ic=''){const e=document.getElementById('toast');e.innerHTML=(ic?ic+' ':'')+m;e.style.pointerEvents=m.includes('<button')?'auto':'none';e.classList.add('show');clearTimeout(_tt);_tt=setTimeout(()=>e.classList.remove('show'),m.includes('<button')?4000:2200);}
window.undoDel=function(){if(!S.delTask)return;const t=S.delTask;if(t.type==='word')S.words.splice(t.i,0,t.w);else if(t.type==='fav')S.favorites.splice(t.i,0,t.w);else if(t.type==='cfav'){S.favorites=t.oldF;S.favTab=t.oldFT;}S.delTask=null;sv();render();document.getElementById('toast').classList.remove('show');setTimeout(()=>toast('已撤銷','↩️'),200);};
function speak(t,l='ja-JP'){if(!window.speechSynthesis)return toast('不支持語音','⚠️');window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang=l;u.rate=0.8;window.speechSynthesis.speak(u);}
async function pdfLoad(f){const lib=window['pdfjs-dist/build/pdf'];if(!lib)return toast('PDF.js未加載','⚠️');lib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';toast('提取中...','⏳');try{const pdf=await lib.getDocument({data:await f.arrayBuffer()}).promise;let t='';for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i);const c=await p.getTextContent();t+=c.items.map(x=>x.str).join('')+'\n';}const ta=document.getElementById('ITA');if(ta)ta.value=t;toast(`${pdf.numPages}頁提取完成，請整理後導入`,'📄');}catch(e){toast('讀取失敗: '+e.message,'❌');}}
function bnk(id){return S.banks.find(b=>b.id===id)||S.banks[0];}
function dup(jp,cn){return S.words.some(w=>w.jp===jp&&w.cn===cn);}
function fved(w){return S.favorites.some(f=>f.jp===w.jp&&f.cn===w.cn);}
function shuf(a){const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]];}return r;}
function tHdr(){return `<header><div class="logo"><div class="lico">🗾</div><div><h1>単語カード</h1><p>日語單詞閃卡</p></div></div><div class="hnav"><button class="thb" id="Bth">${S.theme==='dark'?'☀️':'🌙'}</button><button class="nb ${S.view!=='favs'?'on':''}" id="Bhm2">📚 詞庫</button><button class="nb ${S.view==='favs'?'on':''}" id="Bfv2">⭐ 收藏${S.favorites.length?` (${S.favorites.length})`:''}</button></div></header>`;}
function tHome(){const ws=S.libTab==='all'?S.words:S.words.filter(w=>w.bankId===S.libTab);const wc=ws.length;return `<div class="ani"><div class="tabs"><button class="tb ${S.tab==='i'?'on':''}" data-tb="i">✏️ 輸入</button><button class="tb ${S.tab==='m'?'on':''}" data-tb="m">📥 導入</button><button class="tb ${S.tab==='s'?'on':''}" data-tb="s">🎲 抽查</button><button class="tb ${S.tab==='b'?'on':''}" data-tb="b">🗂 分類</button></div>
<div class="tp ${S.tab==='i'?'on':''}"><div class="pn"><div class="pt">✏️ 添加單詞</div><div style="display:grid;grid-template-columns:1fr 1fr auto;gap:9px"><input class="inp" id="Ij" placeholder="日語（桜）"><input class="inp" id="Ir" placeholder="讀音（さくら）"><input class="inp" id="Ic" placeholder="中文（櫻花）" style="grid-column:1/3"><div style="display:grid;gap:7px"><select class="inp" id="Ib" style="font-size:12px">${S.banks.map(b=>`<option value="${b.id}">${b.name}</option>`).join('')}</select><button class="btn ba" id="Badd" style="justify-content:center">＋ 添加</button></div></div></div></div>
<div class="tp ${S.tab==='m'?'on':''}"><div class="pn"><div class="pt">📥 批量導入</div><div style="display:flex;gap:8px;margin-bottom:10px;align-items:center;flex-wrap:wrap"><span style="font-size:12px;color:var(--t2)">分類：</span><select class="inp" id="IBb" style="width:auto;flex:1;font-size:12px">${S.banks.map(b=>`<option value="${b.id}"${S.iBid===b.id?' selected':''}>${b.name}</option>`).join('')}</select><label class="btn bs" style="cursor:pointer;font-size:12px">📎 PDF<input type="file" accept=".pdf" id="Ipdf" style="display:none"></label></div><textarea class="inp" id="ITA" placeholder="每行：日語,讀音,中文（讀音可空）&#10;例：桜,さくら,櫻花"></textarea><p style="font-size:11px;color:var(--t3);margin:6px 0 10px">💡 逗號/分號分隔，重複單詞將自動跳過</p><div style="display:flex;gap:8px"><button class="btn ba" id="Bim">📥 導入</button><button class="btn bs" id="Bsp">📝 示例</button></div></div><div class="pn" style="margin-top:12px"><div class="pt" style="margin-bottom:6px">💾 數據備份與同步</div><div style="font-size:12px;color:var(--t3);margin-bottom:12px;line-height:1.4">導出文件到本地，或將文件發送到其他設備恢復以實現進度互通。</div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn bs" id="BExp">💾 導出數據 (.json)</button><label class="btn bs" style="cursor:pointer;margin:0">📂 恢復數據<input type="file" accept=".json" id="IImp" style="display:none"></label></div></div></div>
<div class="tp ${S.tab==='s'?'on':''}"><div class="pn"><div class="pt">⚙️ 抽查設置</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px"><div><label style="font-size:11px;color:var(--t2);font-weight:600;display:block;margin-bottom:6px">數量</label><div class="cnt"><button class="cnb" id="Bmi">−</button><input type="number" class="ci" id="Ic2" value="${S.qC}" min="1"><button class="cnb" id="Bpl">＋</button></div></div><div><label style="font-size:11px;color:var(--t2);font-weight:600;display:block;margin-bottom:6px">模式</label><div class="mds"><div class="md ${S.qM==='jp'?'on':''}" data-md="jp">🇯🇵 日→中</div><div class="md ${S.qM==='cn'?'on':''}" data-md="cn">🇨🇳 中→日</div></div></div></div><div style="margin-bottom:12px"><label style="font-size:11px;color:var(--t2);font-weight:600;display:block;margin-bottom:6px">範圍</label><div class="mds"><div class="md ${S.qSrc!=='fav'?'on':''}" data-qs="all">📚 全詞庫</div><div class="md ${S.qSrc==='fav'?'on':''}" data-qs="fav">⭐ 僅收藏</div></div></div><div><div style="font-size:11px;color:var(--t2);font-weight:600;margin-bottom:5px">篩選分類（不選=全部）</div><div class="bcks">${S.banks.map(b=>{const on=S.qBids.includes(b.id);return`<div class="bck ${on?'on':''}" data-bc="${b.id}" style="${on?`background:${b.color};border-color:${b.color}`:''}"><span style="width:7px;height:7px;border-radius:50%;background:${b.color};display:inline-block"></span>${b.name}</div>`;}).join('')}</div></div></div><div style="text-align:center;margin-top:8px"><button class="stb" id="Bst" ${(S.qSrc==='fav'?S.favorites.length:wc)===0?'disabled':''}>🎌 開始抽查</button><p style="margin-top:7px;font-size:12px;color:var(--t3)">${(S.qSrc==='fav'?S.favorites.length:wc)===0?'沒有可抽查的單詞':'共 '+(S.qSrc==='fav'?S.favorites.length:wc)+' 個單詞'}</p></div></div>
<div class="tp ${S.tab==='b'?'on':''}"><div class="pn"><div class="pt">🗂 分類管理</div><div style="display:flex;flex-wrap:wrap;gap:7px;margin-bottom:12px">${S.banks.map((b,i)=>`<div style="display:flex;align-items:center;gap:6px;padding:5px 11px;border-radius:20px;border:1px solid var(--bd);background:var(--s2);font-size:12px"><span style="width:9px;height:9px;border-radius:50%;background:${b.color}"></span>${b.name}<span style="color:var(--t3)">(${S.words.filter(w=>w.bankId===b.id).length})</span>${i>=4?`<button class="dx" data-db="${b.id}">✕</button>`:''}</div>`).join('')}</div><div style="display:flex;gap:8px"><input class="inp" id="Inb" placeholder="新分類名稱" style="flex:1"><button class="btn ba" id="Bnb" style="white-space:nowrap">＋ 添加</button></div></div></div>
<div class="pn"><div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px"><div class="pt" style="margin:0">📖 單詞庫 <span id="WcSpan" style="background:var(--a);color:#fff;padding:2px 9px;border-radius:20px;font-size:11px;font-weight:700">${wc}</span></div><div style="display:flex;gap:8px;align-items:center"><input class="inp" id="Isk" placeholder="🔍 搜索..." value="${(S.sk||'').replace(/"/g,'&quot;')}" style="padding:4px 10px;font-size:12px;width:130px;border-radius:8px;border-color:transparent;background:var(--bg2)"><button class="btn bs" id="Bclr" style="font-size:11px;padding:5px 10px">✕ 清空</button></div></div><div class="ftbs"><div class="ftb ${S.libTab==='all'?'on':''}" data-lt="all">全部(${S.words.length})</div>${S.banks.map(b=>{const c=S.words.filter(w=>w.bankId===b.id).length;return c>0?`<div class="ftb ${S.libTab===b.id?'on':''}" data-lt="${b.id}" style="${S.libTab===b.id?`background:${b.color};border-color:${b.color}`:''}"><span style="width:6px;height:6px;border-radius:50%;background:${b.color};display:inline-block;margin-right:2px"></span>${b.name}(${c})</div>`:'';}).join('')}</div><div class="wg">${wc===0?'<div style="color:var(--t3);font-size:13px;padding:14px;text-align:center;grid-column:1/-1">還沒有單詞 🌸</div>':ws.map((w)=>{const i=S.words.indexOf(w);const b=bnk(w.bankId);const fv=fved(w);return`<div class="wc" data-wi="${i}">${fv?'<span class="wcf">⭐</span>':''}<button class="wcd" data-di="${i}">✕</button><div class="wcj">${w.jp}</div><div class="wcr">${w.reading||' '}</div><div class="wcc">${w.cn}</div><span style="display:inline-flex;align-items:center;gap:3px;margin-top:5px;padding:2px 7px;border-radius:10px;background:${b.color}22;font-size:9px;font-weight:600;color:${b.color}"><span style="width:5px;height:5px;border-radius:50%;background:${b.color};display:inline-block"></span>${b.name}</span></div>`;}).join('')}</div></div></div>`;}

function tQuiz(){const w=S.qW[S.qi];const tot=S.qW.length;const jp=S.qM==='jp';const ft=jp?w.jp:w.cn;const bt=jp?w.cn:w.jp;const fv=fved(w);const fs=jp?`font-family:'Noto Serif JP',serif;font-size:${ft.length>5?34:44}px`:'font-size:24px;font-weight:600';const b=bnk(w.bankId);const bh=b.id!=='g'?`<div style="margin-top:12px;"><span class="bb" style="background:${b.color}44;color:${b.color};border:1px solid ${b.color}44">${b.name}</span></div>`:'';return `<div class="ani"><div class="qh"><div><div class="qpg">${S.qi+1} / ${tot}</div><div class="qsb">${jp?'日語→中文':'中文→日語'}</div></div><div class="pbw"><div class="pb" style="width:${(S.qi/tot)*100}%"></div></div><button class="btn bs" id="Bex" style="font-size:12px;padding:7px 12px">✕ 退出</button></div><div class="ca"><div class="fc ${S.qF?'flip':''}" id="FC"><div class="cface crft"><div class="clbl">${jp?'日語':'中文'}</div><div style="${fs}">${ft}</div>${jp&&w.reading?`<div class="crdn">${w.reading}</div>`:''}<div class="ctap">👆 點擊翻轉</div>${jp?`<button class="ttsbtn" id="Bts1">🔊 朗讀</button>`:''}</div><div class="cface crbk"><div class="clbl">${jp?'中文':'日語'}</div><div style="${jp?'font-size:24px;font-weight:600':fs}">${bt}</div>${!jp&&w.reading?`<div class="crdn">${w.reading}</div>`:''}<div class="crdn" style="font-size:12px;margin-top:8px;color:var(--t3)">${jp&&w.reading?`📖 ${w.jp}（${w.reading}）`:(!jp&&w.reading?`📖 ${w.reading}`:'')}</div>${bh}${!jp?`<button class="ttsbtn" id="Bts2">🔊 朗讀</button>`:''}</div></div></div><div class="acts"><button class="act" id="Bpv" style="opacity:${S.qi>0?1:.3}">◀<span>上一張</span></button><button class="act ${fv?'astr':''}" id="Bfav">${fv?'★':'☆'}<span>${fv?'已收藏':'收藏'}</span></button><button class="act anxt" id="Bnx">▶<span>下一張</span></button></div></div>`;}
function tDone(){return `<div class="ani"><div class="qh"><div><div class="qpg">${S.qW.length}/${S.qW.length}</div><div class="qsb">完成</div></div><div class="pbw"><div class="pb" style="width:100%"></div></div><div style="width:90px"></div></div><div class="pn" style="text-align:center;padding:40px 20px"><div style="font-size:56px;margin-bottom:14px">🎉</div><div style="font-size:24px;font-weight:700;margin-bottom:7px">抽查完成！</div><div style="color:var(--t2);font-size:14px;margin-bottom:22px">共 ${S.qW.length} 個，收藏了 ${S.qNF} 個</div><div style="display:flex;justify-content:center;gap:22px;margin-bottom:26px"><div style="text-align:center"><div style="font-size:28px;font-weight:700;color:var(--a2)">${S.qW.length}</div><div style="font-size:12px;color:var(--t3)">抽查數</div></div><div style="text-align:center"><div style="font-size:28px;font-weight:700;color:var(--g)">${S.qNF}</div><div style="font-size:12px;color:var(--t3)">已收藏</div></div></div><div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap"><button class="btn ba" id="Brs">🔄 再抽</button><button class="btn bg" id="Bgf">⭐ 收藏夾</button><button class="btn bs" id="Bhd">🏠 返回</button></div></div></div>`;}
function tFavs(){const fs=S.favTab==='all'?S.favorites:S.favorites.filter(f=>f.bankId===S.favTab);return `<div class="ani"><div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:14px"><div class="pt" style="margin:0">⭐ 收藏夾 <span id="FvWcSpan" style="background:var(--a);color:#fff;padding:2px 9px;border-radius:20px;font-size:11px;font-weight:700">${fs.length}</span></div><div style="display:flex;gap:6px;align-items:center"><input class="inp" id="IFsk" placeholder="🔍 搜索..." value="${(S.fsk||'').replace(/"/g,'&quot;')}" style="padding:4px 10px;font-size:12px;width:110px;border-radius:8px;border-color:transparent;background:var(--bg2)"><button class="btn bs" id="BFclr" style="font-size:11px;padding:4px 8px;min-width:auto" title="清空搜索">✕</button><button class="btn bd2" id="Bcf" style="font-size:11px;padding:4px 8px;min-width:auto" title="清空所有收藏">🗑</button></div></div><div class="ftbs"><div class="ftb ${S.favTab==='all'?'on':''}" data-ft="all">全部(${S.favorites.length})</div>${S.banks.map(b=>{const c=S.favorites.filter(f=>f.bankId===b.id).length;return c>0?`<div class="ftb ${S.favTab===b.id?'on':''}" data-ft="${b.id}" style="${S.favTab===b.id?`background:${b.color};border-color:${b.color}`:''}"><span style="width:6px;height:6px;border-radius:50%;background:${b.color};display:inline-block;margin-right:2px"></span>${b.name}(${c})</div>`:'';}).join('')}</div>${fs.length===0?`<div class="pn" style="text-align:center;padding:44px"><div style="font-size:42px;margin-bottom:12px">⭐</div><p style="color:var(--t2)">還沒有收藏</p><p style="color:var(--t3);font-size:12px;margin-top:5px">在抽查時點擊收藏按鈕添加</p></div>`:`<div class="fg">${fs.map(w=>{const ri=S.favorites.indexOf(w);const b=bnk(w.bankId);return`<div class="fcd" data-fi="${ri}"><button class="fdl" data-fd="${ri}">✕</button><div class="fjp">${w.jp}</div>${w.reading?`<div class="frd">📖 ${w.reading}</div>`:''}<div class="fcn">${w.cn}</div><span class="bb" style="background:${b.color}44;color:${b.color};border:1px solid ${b.color}44;margin-top:5px">${b.name}</span></div>`;}).join('')}</div>`}</div>`;}
function tWordModal(v){const i=typeof v==='number'?v:v._editIdx;const w=S.words[i];const fv=fved(w);return `<button class="mcl" id="Bmc">✕</button><div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:14px"><div style="font-size:13px;font-weight:700;color:var(--t2);text-transform:uppercase;letter-spacing:1px">✏️ 編輯單詞</div><button id="BwFav" data-wi="${i}" style="background:${fv?'rgba(251,191,36,.15)':'var(--s2)'};border:1px solid ${fv?'var(--g)':'var(--bd)'};color:${fv?'var(--g)':'var(--t2)'};border-radius:9px;padding:5px 11px;cursor:pointer;font-size:13px;font-family:inherit;transition:.2s">${fv?'★ 已收藏':'☆ 收藏'}</button></div><div style="display:grid;gap:9px;margin-bottom:16px"><input class="inp" id="EJp" placeholder="日語" value="${w.jp.replace(/"/g,'&quot;')}"><input class="inp" id="ERd" placeholder="讀音（可空）" value="${(w.reading||'').replace(/"/g,'&quot;')}"><input class="inp" id="ECn" placeholder="中文" value="${w.cn.replace(/"/g,'&quot;')}"><select class="inp" id="EBk">${S.banks.map(b=>`<option value="${b.id}"${w.bankId===b.id?' selected':''} >${b.name}</option>`).join('')}</select></div><div style="display:flex;gap:8px;justify-content:center"><button class="btn ba" id="Bsv" data-si="${i}">💾 保存</button><button class="btn bs" id="Bmc2">${v._fromView?'🔙 返回':'取消'}</button></div>`;}
function tModal(w){const b=bnk(w.bankId);const wi=S.words.findIndex(xw=>xw.jp===w.jp&&xw.cn===w.cn);const fv=fved(w);return `<button class="mcl" id="Bmc">✕</button>${wi!==-1?`<button id="BwFavView" data-wi="${wi}" style="position:absolute;top:14px;left:14px;background:${fv?'rgba(251,191,36,.15)':'var(--s2)'};border:1px solid ${fv?'var(--g)':'var(--bd)'};color:${fv?'var(--g)':'var(--t2)'};border-radius:9px;padding:4px 9px;cursor:pointer;font-size:11px;font-weight:600;font-family:inherit;transition:.2s">${fv?'★ 已收藏':'☆ 收藏'}</button>`:''}<div class="mjp" style="margin-top:10px">${w.jp}</div>${w.reading?`<div class="mrd">📖 ${w.reading}</div>`:''}<div class="mcn">${w.cn}</div><div style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin:12px 0">${w.jp?`<button class="btn ba" onclick="speak('${w.jp.replace(/'/g,"\\'")}')" >🔊 日語</button>`:''} ${w.reading?`<button class="btn bs" onclick="speak('${w.reading.replace(/'/g,"\\'")}')">🔊 假名</button>`:''}${wi!==-1?`<button class="btn bs" id="BwEdit" data-wi="${wi}">✏️ 編輯</button>`:''}</div><span class="bb" style="background:${b.color}44;color:${b.color};border:1px solid ${b.color}44">${b.name}</span>`;}
function render(){const wY=window.scrollY;const app=document.getElementById('app');let c='';if(S.view==='quiz')c=tQuiz();else if(S.view==='done')c=tDone();else if(S.view==='favs')c=tFavs();else c=tHome();app.innerHTML=tHdr()+c;bind();window.scrollTo(0,wY);const MO=document.getElementById('MO');const MC=document.getElementById('MC');if(S.modal&&MO&&MC){MO.classList.remove('hide');if(S.modal._editIdx!==undefined){MC.innerHTML=tWordModal(S.modal);}else{MC.innerHTML=tModal(S.modal);}bindModal();}else if(MO){MO.classList.add('hide');}}
function bind(){const Bth=document.getElementById('Bth');if(Bth)Bth.onclick=()=>{S.theme=S.theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',S.theme);sv();render();};const Bhm2=document.getElementById('Bhm2');if(Bhm2)Bhm2.onclick=()=>{S.view='home';render();};const Bfv2=document.getElementById('Bfv2');if(Bfv2)Bfv2.onclick=()=>{S.view='favs';render();};
document.querySelectorAll('[data-tb]').forEach(el=>el.onclick=()=>{S.tab=el.dataset.tb;render();if(S.tab==='i')setTimeout(()=>document.getElementById('Ij')?.focus(),30);});if(S.view==='home'&&S.tab==='i')setTimeout(()=>document.getElementById('Ij')?.focus(),30);
const Badd=document.getElementById('Badd');if(Badd)Badd.onclick=addWord;
['Ij','Ir','Ic'].forEach((id,i,a)=>{const el=document.getElementById(id);if(!el)return;el.onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing&&e.keyCode!==229){e.preventDefault();if(id==='Ic')addWord();else document.getElementById(a[i+1])?.focus();}};});
const Bim=document.getElementById('Bim');if(Bim)Bim.onclick=doImport;
const Bsp=document.getElementById('Bsp');if(Bsp)Bsp.onclick=()=>{const ta=document.getElementById('ITA');if(ta)ta.value='桜,さくら,櫻花\n東京,とうきょう,東京\n学校,がっこう,學校\n先生,せんせい,老師\n友達,ともだち,朋友\n電車,でんしゃ,電車\n食べる,たべる,吃\n飲む,のむ,喝\n見る,みる,看\n聞く,きく,聽';toast('示例已載入','📝');};
const Ipdf=document.getElementById('Ipdf');if(Ipdf)Ipdf.onchange=e=>{if(e.target.files[0])pdfLoad(e.target.files[0]);};
const IBb=document.getElementById('IBb');if(IBb)IBb.onchange=()=>{S.iBid=IBb.value;};
const BExp=document.getElementById('BExp');if(BExp)BExp.onclick=doExport;
const IImp=document.getElementById('IImp');if(IImp)IImp.onchange=e=>{if(e.target.files[0]){doImportFile(e.target.files[0]);e.target.value='';}};
const Bmi=document.getElementById('Bmi');if(Bmi)Bmi.onclick=()=>{S.qC=Math.max(1,S.qC-1);const el=document.getElementById('Ic2');if(el)el.value=S.qC;};
const Bpl=document.getElementById('Bpl');if(Bpl)Bpl.onclick=()=>{let mx=S.qSrc==='fav'?S.favorites.length:S.words.length;S.qC=Math.min(mx||1,S.qC+1);const el=document.getElementById('Ic2');if(el)el.value=S.qC;};
const Ic2=document.getElementById('Ic2');if(Ic2)Ic2.onchange=()=>{let mx=S.qSrc==='fav'?S.favorites.length:S.words.length;let v=parseInt(Ic2.value)||1;v=Math.max(1,Math.min(mx||1,v));S.qC=v;Ic2.value=v;};
document.querySelectorAll('[data-md]').forEach(el=>el.onclick=()=>{S.qM=el.dataset.md;render();});
document.querySelectorAll('[data-qs]').forEach(el=>el.onclick=()=>{S.qSrc=el.dataset.qs;render();});
document.querySelectorAll('[data-bc]').forEach(el=>el.onclick=()=>{const id=el.dataset.bc;if(S.qBids.includes(id))S.qBids=S.qBids.filter(x=>x!==id);else S.qBids.push(id);render();});document.querySelectorAll('[data-lt]').forEach(el=>el.onclick=()=>{S.libTab=el.dataset.lt;render();});
const Bst=document.getElementById('Bst');if(Bst)Bst.onclick=startQ;
document.querySelectorAll('[data-di]').forEach(el=>el.onclick=(e)=>{e.stopPropagation();const i=parseInt(el.dataset.di);const w=S.words[i];S.words.splice(i,1);sv();render();S.delTask={type:'word',i,w};toast(`「${w.jp}」已刪除 <button onclick="undoDel()" style="margin-left:8px;padding:3px 8px;border-radius:6px;border:1px solid rgba(255,255,255,0.3);background:transparent;color:inherit;cursor:pointer;font-size:11px">撤銷</button>`,'🗑');});document.querySelectorAll('[data-wi]').forEach(el=>el.onclick=(e)=>{if(e.target.closest('[data-di]'))return;const i=parseInt(el.dataset.wi);S.modal=S.words[i];render();});
const Isk=document.getElementById('Isk');if(Isk){const doSearch=()=>{const k=S.sk;let c=0;document.querySelectorAll('.wg .wc').forEach(el=>{if(!k||el.textContent.toLowerCase().includes(k)){el.style.display='';c++;}else{el.style.display='none';}});const dsLen=S.libTab==='all'?S.words.length:S.words.filter(w=>w.bankId===S.libTab).length;const sp=document.getElementById('WcSpan');if(sp)sp.textContent=k?(c+' / '+dsLen):dsLen;};Isk.oninput=e=>{S.sk=e.target.value.toLowerCase().trim();doSearch();};if(S.sk)doSearch();}
const Bclr=document.getElementById('Bclr');if(Bclr)Bclr.onclick=()=>{S.sk='';const el=document.getElementById('Isk');if(el){el.value='';el.dispatchEvent(new Event('input'));}};
const Bnb=document.getElementById('Bnb');if(Bnb)Bnb.onclick=addBank;
document.querySelectorAll('[data-db]').forEach(el=>el.onclick=()=>{const id=el.dataset.db;if(confirm('刪除此分類？其中單詞將移至一般詞彙')){S.words=S.words.map(w=>w.bankId===id?{...w,bankId:'g'}:w);S.favorites=S.favorites.map(f=>f.bankId===id?{...f,bankId:'g'}:f);S.banks=S.banks.filter(b=>b.id!==id);sv();render();toast('分類已刪除','🗑');}});
if(S.view==='quiz'){const FC=document.getElementById('FC');if(FC)FC.onclick=()=>{S.qF=!S.qF;FC.classList.toggle('flip',S.qF);};const Bts1=document.getElementById('Bts1');if(Bts1)Bts1.onclick=e=>{e.stopPropagation();speak(S.qW[S.qi].jp);};const Bts2=document.getElementById('Bts2');if(Bts2)Bts2.onclick=e=>{e.stopPropagation();speak(S.qW[S.qi].jp);};const Bex=document.getElementById('Bex');if(Bex)Bex.onclick=()=>{S.view='home';render();};const Bpv=document.getElementById('Bpv');if(Bpv)Bpv.onclick=()=>{if(S.qi>0){S.qi--;S.qF=false;render();}};const Bfav=document.getElementById('Bfav');if(Bfav)Bfav.onclick=togFav;const Bnx=document.getElementById('Bnx');if(Bnx)Bnx.onclick=nextCard;}
if(S.view==='done'){const Brs=document.getElementById('Brs');if(Brs)Brs.onclick=()=>{S.qW=shuf(S.qW);S.qi=0;S.qF=false;S.qNF=0;S.view='quiz';render();};const Bgf=document.getElementById('Bgf');if(Bgf)Bgf.onclick=()=>{S.view='favs';render();};const Bhd=document.getElementById('Bhd');if(Bhd)Bhd.onclick=()=>{S.view='home';render();};}
if(S.view==='favs'){document.querySelectorAll('[data-ft]').forEach(el=>el.onclick=()=>{S.favTab=el.dataset.ft;render();});document.querySelectorAll('[data-fi]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-fd]'))return;const w=S.favorites[parseInt(el.dataset.fi)];if(w){S.modal=w;render();}});document.querySelectorAll('[data-fd]').forEach(el=>el.onclick=e=>{e.stopPropagation();const i=parseInt(el.dataset.fd);const w=S.favorites[i];S.favorites.splice(i,1);sv();render();S.delTask={type:'fav',i,w};toast(`「${w.jp}」已移除 <button onclick="undoDel()" style="margin-left:8px;padding:3px 8px;border-radius:6px;border:1px solid rgba(255,255,255,0.3);background:transparent;color:inherit;cursor:pointer;font-size:11px">撤銷</button>`,'💔');});const Bcf=document.getElementById('Bcf');if(Bcf)Bcf.onclick=()=>{if(confirm('清空所有收藏？')){const oldF=[...S.favorites];const oldFT=S.favTab;S.favorites=[];S.favTab='all';sv();render();S.delTask={type:'cfav',oldF,oldFT};toast(`收藏已清空 <button onclick="undoDel()" style="margin-left:8px;padding:3px 8px;border-radius:6px;border:1px solid rgba(255,255,255,0.3);background:transparent;color:inherit;cursor:pointer;font-size:11px">撤銷</button>`,'🗑');}};const IFsk=document.getElementById('IFsk');if(IFsk){const doFvSearch=()=>{const k=S.fsk;let c=0;document.querySelectorAll('.fg .fcd').forEach(el=>{if(!k||el.textContent.toLowerCase().includes(k)){el.style.display='';c++;}else{el.style.display='none';}});const dsLen=S.favTab==='all'?S.favorites.length:S.favorites.filter(f=>f.bankId===S.favTab).length;const sp=document.getElementById('FvWcSpan');if(sp)sp.textContent=k?(c+' / '+dsLen):dsLen;};IFsk.oninput=e=>{S.fsk=e.target.value.toLowerCase().trim();doFvSearch();};if(S.fsk)doFvSearch();}const BFclr=document.getElementById('BFclr');if(BFclr)BFclr.onclick=()=>{S.fsk='';const el=document.getElementById('IFsk');if(el){el.value='';el.dispatchEvent(new Event('input'));}};};
const Bmc=document.getElementById('Bmc');if(Bmc)Bmc.onclick=()=>{S.modal=null;render();};}
function moClose(e){if(e.target.id==='MO'){S.modal=null;render();}}
function bindModal(){const Bmc=document.getElementById('Bmc');if(Bmc)Bmc.onclick=()=>{S.modal=null;render();};const Bmc2=document.getElementById('Bmc2');if(Bmc2)Bmc2.onclick=()=>{if(S.modal&&S.modal._fromView&&S.modal._editIdx!==undefined)S.modal=S.words[S.modal._editIdx];else S.modal=null;render();};const Bsv=document.getElementById('Bsv');if(Bsv){const si=parseInt(Bsv.dataset.si);Bsv.onclick=()=>saveEdit(si);}const BwFav=document.getElementById('BwFav');if(BwFav){const wi=parseInt(BwFav.dataset.wi);BwFav.onclick=()=>{const w=S.words[wi];if(fved(w)){S.favorites=S.favorites.filter(f=>!(f.jp===w.jp&&f.cn===w.cn));toast(`「${w.jp}」已取消收藏`,'💔');}else{S.favorites.push({...w});toast(`「${w.jp}」已加入收藏！`,'⭐');}sv();S.modal={_editIdx:wi,_fromView:S.modal._fromView};render();};}const BwFavView=document.getElementById('BwFavView');if(BwFavView){const wi=parseInt(BwFavView.dataset.wi);BwFavView.onclick=()=>{const w=S.words[wi];if(fved(w)){S.favorites=S.favorites.filter(f=>!(f.jp===w.jp&&f.cn===w.cn));toast(`「${w.jp}」已取消收藏`,'💔');}else{S.favorites.push({...w});toast(`「${w.jp}」已加入收藏！`,'⭐');}sv();S.modal=S.words[wi];render();};}const BwEdit=document.getElementById('BwEdit');if(BwEdit){const wi=parseInt(BwEdit.dataset.wi);BwEdit.onclick=()=>{S.modal={_editIdx:wi,_fromView:true};render();};}}
function saveEdit(i){const jp=(document.getElementById('EJp')?.value||'').trim();const rd=(document.getElementById('ERd')?.value||'').trim();const cn=(document.getElementById('ECn')?.value||'').trim();const bid=document.getElementById('EBk')?.value||'g';if(!jp||!cn)return toast('請填日語和中文！','⚠️');const old=S.words[i];S.words[i]={...old,jp,reading:rd,cn,bankId:bid};S.favorites=S.favorites.map(f=>(f.jp===old.jp&&f.cn===old.cn)?{...f,jp,reading:rd,cn,bankId:bid}:f);if(S.modal&&S.modal._fromView)S.modal=S.words[i];else S.modal=null;sv();render();toast(`「${jp}」已更新`,'✅');}
function addWord(){const jp=(document.getElementById('Ij')?.value||'').trim();const rd=(document.getElementById('Ir')?.value||'').trim();const cn=(document.getElementById('Ic')?.value||'').trim();const bid=document.getElementById('Ib')?.value||'g';if(!jp||!cn)return toast('請填日語和中文！','⚠️');if(dup(jp,cn))return toast(`「${jp}」已存在，已跳過`,'ℹ️');S.words.push({jp,reading:rd,cn,bankId:bid});S.qC=Math.min(S.qC||10,S.words.length);sv();render();toast(`「${jp}」已添加`,'✅');setTimeout(()=>document.getElementById('Ij')?.focus(),10);}
function doImport(){const text=(document.getElementById('ITA')?.value||'').trim();const bid=document.getElementById('IBb')?.value||S.iBid||'g';if(!text)return toast('請先輸入單詞','⚠️');let added=0,skipped=0;text.split('\n').filter(l=>l.trim()).forEach(line=>{const parts=line.split(/[,，;；]/).map(s=>s.trim());if(parts.length>=2){const jp=parts[0];let rd='',cn='';if(parts.length>=3){rd=parts[1];cn=parts[2];}else{cn=parts[1];}if(jp&&cn){if(dup(jp,cn)){skipped++;}else{S.words.push({jp,reading:rd,cn,bankId:bid});added++;}}}});S.qC=Math.min(S.qC||10,S.words.length);sv();render();toast(`導入 ${added} 個${skipped?`，跳過 ${skipped} 重複`:''}`,added>0?'🎉':'⚠️');}
function doExport(){const data=JSON.stringify({w:S.words,f:S.favorites,b:S.banks,t:S.theme});const blob=new Blob([data],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;const d=new Date();const dStr=d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0');a.download=`tango_backup_${dStr}.json`;a.click();URL.revokeObjectURL(url);toast('備份已導出','💾');}
function doImportFile(file){const reader=new FileReader();reader.onload=e=>{try{const data=JSON.parse(e.target.result);if(data.w&&data.b){if(!confirm('將覆蓋當前所有數據，確定恢復嗎？'))return;S.words=data.w||[];S.favorites=data.f||[];S.banks=data.b||BD;S.theme=data.t||'dark';sv();document.documentElement.setAttribute('data-theme',S.theme);render();toast('數據已成功恢復！','🎉');}else{toast('備份文件格式不正确','❌');}}catch{toast('讀取失敗，請確保是有效的 JSON 文件','❌');}};reader.readAsText(file);}
function startQ(){let base=S.qSrc==='fav'?S.favorites:S.words;if(!base.length)return toast(S.qSrc==='fav'?'請先收藏單詞':'請先添加單詞','⚠️');let pool=base;if(S.qBids.length)pool=pool.filter(w=>S.qBids.includes(w.bankId));if(!pool.length)return toast('所選分類無單詞','⚠️');const count=Math.max(1,Math.min(S.qC,pool.length));S.qW=shuf(pool).slice(0,count);S.qi=0;S.qF=false;S.qNF=0;S.view='quiz';render();}
function nextCard(){if(S.qi<S.qW.length-1){S.qi++;S.qF=false;S.view='quiz';render();}else{S.view='done';render();}}
function togFav(){const w=S.qW[S.qi];if(fved(w)){S.favorites=S.favorites.filter(f=>!(f.jp===w.jp&&f.cn===w.cn));toast(`「${w.jp}」已取消收藏`,'💔');}else{S.favorites.push({...w});S.qNF++;toast(`「${w.jp}」已加入收藏！`,'⭐');}sv();render();}
function addBank(){const nm=(document.getElementById('Inb')?.value||'').trim();if(!nm)return toast('請輸入分類名稱','⚠️');if(S.banks.some(b=>b.name===nm))return toast('分類已存在','ℹ️');const colors=['#7c6af7','#34d399','#f472b6','#60a5fa','#fb923c','#a78bfa','#f59e0b','#ec4899'];const color=colors[S.banks.length%colors.length];const id='u'+Date.now();S.banks.push({id,name:nm,color});sv();render();toast(`分類「${nm}」已建立`,'🗂');}
ld();render();
